// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Task_2.EF;

namespace Task_2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210622142353__init")]
    partial class _init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Task_2.Models.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8264b79c-4904-4dc6-b680-4b697b8ba649"),
                            Gender = 0,
                            LastName = "Ivanovich",
                            Name = "Ivan"
                        },
                        new
                        {
                            Id = new Guid("1dfeb5ca-828f-4bbb-ba26-e2e18ca38425"),
                            Gender = 0,
                            LastName = "Petrov",
                            Name = "Peter"
                        },
                        new
                        {
                            Id = new Guid("492661c5-3581-4ddc-ae38-8a431c615a4d"),
                            Gender = 0,
                            LastName = "Yuriyovich",
                            Name = "Yuriy"
                        },
                        new
                        {
                            Id = new Guid("8948a3d2-e7a7-4519-baf8-0befaf1c80b1"),
                            Gender = 0,
                            LastName = "Eugenievich",
                            Name = "Eugen"
                        },
                        new
                        {
                            Id = new Guid("c9adb4d2-d5b3-45e7-82c1-79bcd8afb032"),
                            Gender = 0,
                            LastName = "Denisovich",
                            Name = "Denis"
                        },
                        new
                        {
                            Id = new Guid("f7f229dd-b479-48a8-a6ab-4379db57d7f4"),
                            Gender = 0,
                            LastName = "Dmitrivich",
                            Name = "Dmitrii"
                        },
                        new
                        {
                            Id = new Guid("28f23c8e-85a4-4da3-8fa4-e6f954748066"),
                            Gender = 1,
                            LastName = "Ivanova",
                            Name = "Mirina"
                        },
                        new
                        {
                            Id = new Guid("ebd29ece-d978-4936-812e-338357962351"),
                            Gender = 1,
                            LastName = "Petrova",
                            Name = "Alina"
                        },
                        new
                        {
                            Id = new Guid("e29fdac2-c957-4aad-b9b6-9ea44efd5c70"),
                            Gender = 1,
                            LastName = "Sofievna",
                            Name = "Sofia"
                        });
                });

            modelBuilder.Entity("Task_2.Models.ClientCar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Mileage")
                        .HasColumnType("int");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("YearProduction")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("VehicleId");

                    b.ToTable("ClientCars");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f6c324b7-48d4-405c-91ae-4a4498f17ff4"),
                            ClientId = new Guid("8264b79c-4904-4dc6-b680-4b697b8ba649"),
                            Mileage = 500000,
                            VehicleId = new Guid("192b609c-193a-4b74-94db-8417326fb1bd"),
                            YearProduction = 2000
                        },
                        new
                        {
                            Id = new Guid("58a95b38-f6bc-4300-8a8f-210dd8f8e708"),
                            ClientId = new Guid("1dfeb5ca-828f-4bbb-ba26-e2e18ca38425"),
                            Mileage = 30000,
                            VehicleId = new Guid("b0416954-6776-482f-be10-86211058ce42"),
                            YearProduction = 2018
                        },
                        new
                        {
                            Id = new Guid("8d1bf6f4-b11d-4487-a61a-014fa92beaff"),
                            ClientId = new Guid("492661c5-3581-4ddc-ae38-8a431c615a4d"),
                            Mileage = 140000,
                            VehicleId = new Guid("25aedead-16f6-40ac-9989-ba27488a9e4c"),
                            YearProduction = 2014
                        },
                        new
                        {
                            Id = new Guid("60e27d5e-5d77-4b13-b85e-648aee62644c"),
                            ClientId = new Guid("8948a3d2-e7a7-4519-baf8-0befaf1c80b1"),
                            Mileage = 180000,
                            VehicleId = new Guid("d1fe4900-52f9-4305-94ec-77b775c452f4"),
                            YearProduction = 2011
                        },
                        new
                        {
                            Id = new Guid("3d8dc43e-82aa-4090-a232-1c5abbd199e0"),
                            ClientId = new Guid("c9adb4d2-d5b3-45e7-82c1-79bcd8afb032"),
                            Mileage = 320000,
                            VehicleId = new Guid("d5c40dea-d425-435e-a2e4-b69eadf5e9ca"),
                            YearProduction = 2005
                        },
                        new
                        {
                            Id = new Guid("62df00af-d7e6-4355-b06c-24ac0d2f55d4"),
                            ClientId = new Guid("f7f229dd-b479-48a8-a6ab-4379db57d7f4"),
                            Mileage = 447000,
                            VehicleId = new Guid("d395273f-120a-4779-bd6a-8b2c16c5e3f5"),
                            YearProduction = 2003
                        },
                        new
                        {
                            Id = new Guid("1f0dbb22-afa9-4d9e-ae32-ead056709e91"),
                            ClientId = new Guid("28f23c8e-85a4-4da3-8fa4-e6f954748066"),
                            Mileage = 250000,
                            VehicleId = new Guid("563a405a-e63b-421c-ba5a-e081131f57b1"),
                            YearProduction = 2009
                        },
                        new
                        {
                            Id = new Guid("c82c2016-ed72-44e9-9386-624ee6e11804"),
                            ClientId = new Guid("ebd29ece-d978-4936-812e-338357962351"),
                            Mileage = 5000,
                            VehicleId = new Guid("72e078bd-cb2b-44e6-83c7-1442098f536b"),
                            YearProduction = 2020
                        },
                        new
                        {
                            Id = new Guid("1dfada18-5fac-4ef7-9e9c-5c14e1e9e27d"),
                            ClientId = new Guid("e29fdac2-c957-4aad-b9b6-9ea44efd5c70"),
                            Mileage = 70000,
                            VehicleId = new Guid("cba5843f-9132-434b-ad1c-67d2bb7b9527"),
                            YearProduction = 2017
                        },
                        new
                        {
                            Id = new Guid("db90a95a-64ef-4827-a0ad-809343764eb1"),
                            ClientId = new Guid("8264b79c-4904-4dc6-b680-4b697b8ba649"),
                            Mileage = 35000,
                            VehicleId = new Guid("effeff1e-de70-4c17-8dd0-aad1beb60ca0"),
                            YearProduction = 2019
                        },
                        new
                        {
                            Id = new Guid("e9081a54-05eb-4299-a16f-9f718fb3620e"),
                            ClientId = new Guid("1dfeb5ca-828f-4bbb-ba26-e2e18ca38425"),
                            Mileage = 540000,
                            VehicleId = new Guid("b787d15d-7ab0-440c-97fd-058576566ab4"),
                            YearProduction = 2004
                        },
                        new
                        {
                            Id = new Guid("0bb7d2d2-b932-449c-bd53-35cfa941f573"),
                            ClientId = new Guid("492661c5-3581-4ddc-ae38-8a431c615a4d"),
                            Mileage = 610000,
                            VehicleId = new Guid("e77990f8-4a55-4bea-a861-9fe8e40ed65a"),
                            YearProduction = 2001
                        },
                        new
                        {
                            Id = new Guid("22ceffb5-52b8-4bf8-9473-3a9695724a25"),
                            ClientId = new Guid("8948a3d2-e7a7-4519-baf8-0befaf1c80b1"),
                            Mileage = 340000,
                            VehicleId = new Guid("192b609c-193a-4b74-94db-8417326fb1bd"),
                            YearProduction = 2007
                        },
                        new
                        {
                            Id = new Guid("4574ad1e-0739-4daf-9112-5db7eed8df02"),
                            ClientId = new Guid("c9adb4d2-d5b3-45e7-82c1-79bcd8afb032"),
                            Mileage = 142000,
                            VehicleId = new Guid("25aedead-16f6-40ac-9989-ba27488a9e4c"),
                            YearProduction = 2016
                        },
                        new
                        {
                            Id = new Guid("947b36bf-de7e-45d4-9be3-e3f2a46a00db"),
                            ClientId = new Guid("f7f229dd-b479-48a8-a6ab-4379db57d7f4"),
                            Mileage = 210000,
                            VehicleId = new Guid("d5c40dea-d425-435e-a2e4-b69eadf5e9ca"),
                            YearProduction = 2015
                        });
                });

            modelBuilder.Entity("Task_2.Models.Engine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("EnginePower")
                        .HasColumnType("int");

                    b.Property<int>("EngineType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Engine");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a7ee20c4-7e96-4041-93ff-aec8c3545b44"),
                            EnginePower = 150,
                            EngineType = 0,
                            Name = "asd"
                        },
                        new
                        {
                            Id = new Guid("4b17a8a4-9b8e-4387-86c6-22b937f0f0a6"),
                            EnginePower = 180,
                            EngineType = 0,
                            Name = "wbf"
                        },
                        new
                        {
                            Id = new Guid("09539ab3-c061-4d5e-b8df-87d004e72c4d"),
                            EnginePower = 120,
                            EngineType = 0,
                            Name = "tsn"
                        },
                        new
                        {
                            Id = new Guid("79e5314a-b408-4777-8130-50accddc6aa4"),
                            EnginePower = 210,
                            EngineType = 2,
                            Name = "jnf"
                        },
                        new
                        {
                            Id = new Guid("3e075a48-9b6d-4461-8c8e-f79ef462db2b"),
                            EnginePower = 100,
                            EngineType = 2,
                            Name = "mdf"
                        },
                        new
                        {
                            Id = new Guid("6c4b2c63-a536-4d28-911c-e933e58df8c3"),
                            EnginePower = 110,
                            EngineType = 2,
                            Name = "sms"
                        },
                        new
                        {
                            Id = new Guid("ae04849a-3ce0-4cf4-b241-afa4ca03971f"),
                            EnginePower = 130,
                            EngineType = 3,
                            Name = "krf"
                        },
                        new
                        {
                            Id = new Guid("449233ef-cf17-4e95-beac-3fcf7b5125bd"),
                            EnginePower = 145,
                            EngineType = 3,
                            Name = "xhd"
                        },
                        new
                        {
                            Id = new Guid("3e5069fb-1cb5-4d3b-afc7-6b8842af893c"),
                            EnginePower = 190,
                            EngineType = 3,
                            Name = "tsn"
                        },
                        new
                        {
                            Id = new Guid("bbcd17ce-30de-4f0a-9ec0-ba8dbd6c2682"),
                            EnginePower = 250,
                            EngineType = 1,
                            Name = "rxf"
                        },
                        new
                        {
                            Id = new Guid("4a7a8a98-1f65-41f7-ad51-3196c33ee5d0"),
                            EnginePower = 170,
                            EngineType = 1,
                            Name = "bef"
                        },
                        new
                        {
                            Id = new Guid("ea66b050-2f0f-4184-856e-173de6aaa8af"),
                            EnginePower = 165,
                            EngineType = 1,
                            Name = "ksc"
                        });
                });

            modelBuilder.Entity("Task_2.Models.Transmission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TransmissionType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Transmission");

                    b.HasData(
                        new
                        {
                            Id = new Guid("197822f7-73ae-4761-9b50-2ab9fa3dc0b1"),
                            Name = "dq200",
                            TransmissionType = 0
                        },
                        new
                        {
                            Id = new Guid("4ee53a66-8d84-4045-9eae-78a66a5804d1"),
                            Name = "dq250",
                            TransmissionType = 0
                        },
                        new
                        {
                            Id = new Guid("a1a947d9-3ee1-46a4-9e31-ee50f0122409"),
                            Name = "ndg",
                            TransmissionType = 3
                        },
                        new
                        {
                            Id = new Guid("a8e8b4c9-d5dc-4531-af00-ef7d0e61e520"),
                            Name = "tdv",
                            TransmissionType = 3
                        },
                        new
                        {
                            Id = new Guid("9923a1b7-508b-4028-bfee-b9a4c802e45b"),
                            Name = "dq300",
                            TransmissionType = 1
                        },
                        new
                        {
                            Id = new Guid("061611af-a120-4a2e-9478-9f2d68fdd6c1"),
                            Name = "dq350",
                            TransmissionType = 1
                        },
                        new
                        {
                            Id = new Guid("d05d4a40-7fe2-4f62-aa4a-4cfa7394be7c"),
                            Name = "rcdg",
                            TransmissionType = 2
                        },
                        new
                        {
                            Id = new Guid("3d26cd66-1bd2-42cd-af14-eccc3618be26"),
                            Name = "jydc",
                            TransmissionType = 2
                        });
                });

            modelBuilder.Entity("Task_2.Models.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EngineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TransmissionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EngineId");

                    b.HasIndex("TransmissionId");

                    b.ToTable("Vehicle");

                    b.HasData(
                        new
                        {
                            Id = new Guid("192b609c-193a-4b74-94db-8417326fb1bd"),
                            BrandName = "VW",
                            EngineId = new Guid("a7ee20c4-7e96-4041-93ff-aec8c3545b44"),
                            ModelName = "Passat",
                            TransmissionId = new Guid("197822f7-73ae-4761-9b50-2ab9fa3dc0b1")
                        },
                        new
                        {
                            Id = new Guid("b0416954-6776-482f-be10-86211058ce42"),
                            BrandName = "Subaru",
                            EngineId = new Guid("4b17a8a4-9b8e-4387-86c6-22b937f0f0a6"),
                            ModelName = "Forester",
                            TransmissionId = new Guid("4ee53a66-8d84-4045-9eae-78a66a5804d1")
                        },
                        new
                        {
                            Id = new Guid("25aedead-16f6-40ac-9989-ba27488a9e4c"),
                            BrandName = "Audi",
                            EngineId = new Guid("09539ab3-c061-4d5e-b8df-87d004e72c4d"),
                            ModelName = "Q5",
                            TransmissionId = new Guid("a1a947d9-3ee1-46a4-9e31-ee50f0122409")
                        },
                        new
                        {
                            Id = new Guid("d1fe4900-52f9-4305-94ec-77b775c452f4"),
                            BrandName = "Honda",
                            EngineId = new Guid("79e5314a-b408-4777-8130-50accddc6aa4"),
                            ModelName = "Civic",
                            TransmissionId = new Guid("a8e8b4c9-d5dc-4531-af00-ef7d0e61e520")
                        },
                        new
                        {
                            Id = new Guid("d5c40dea-d425-435e-a2e4-b69eadf5e9ca"),
                            BrandName = "Renault",
                            EngineId = new Guid("3e075a48-9b6d-4461-8c8e-f79ef462db2b"),
                            ModelName = "Logan",
                            TransmissionId = new Guid("9923a1b7-508b-4028-bfee-b9a4c802e45b")
                        },
                        new
                        {
                            Id = new Guid("d395273f-120a-4779-bd6a-8b2c16c5e3f5"),
                            BrandName = "Kia",
                            EngineId = new Guid("6c4b2c63-a536-4d28-911c-e933e58df8c3"),
                            ModelName = "Rio",
                            TransmissionId = new Guid("061611af-a120-4a2e-9478-9f2d68fdd6c1")
                        },
                        new
                        {
                            Id = new Guid("563a405a-e63b-421c-ba5a-e081131f57b1"),
                            BrandName = "Dodge",
                            EngineId = new Guid("ae04849a-3ce0-4cf4-b241-afa4ca03971f"),
                            ModelName = "Ram",
                            TransmissionId = new Guid("d05d4a40-7fe2-4f62-aa4a-4cfa7394be7c")
                        },
                        new
                        {
                            Id = new Guid("72e078bd-cb2b-44e6-83c7-1442098f536b"),
                            BrandName = "BMW",
                            EngineId = new Guid("449233ef-cf17-4e95-beac-3fcf7b5125bd"),
                            ModelName = "Series5",
                            TransmissionId = new Guid("3d26cd66-1bd2-42cd-af14-eccc3618be26")
                        },
                        new
                        {
                            Id = new Guid("cba5843f-9132-434b-ad1c-67d2bb7b9527"),
                            BrandName = "Citroen",
                            EngineId = new Guid("3e5069fb-1cb5-4d3b-afc7-6b8842af893c"),
                            ModelName = "Nemo",
                            TransmissionId = new Guid("4ee53a66-8d84-4045-9eae-78a66a5804d1")
                        },
                        new
                        {
                            Id = new Guid("effeff1e-de70-4c17-8dd0-aad1beb60ca0"),
                            BrandName = "Lada",
                            EngineId = new Guid("bbcd17ce-30de-4f0a-9ec0-ba8dbd6c2682"),
                            ModelName = "Kalina",
                            TransmissionId = new Guid("9923a1b7-508b-4028-bfee-b9a4c802e45b")
                        },
                        new
                        {
                            Id = new Guid("b787d15d-7ab0-440c-97fd-058576566ab4"),
                            BrandName = "Ford",
                            EngineId = new Guid("4a7a8a98-1f65-41f7-ad51-3196c33ee5d0"),
                            ModelName = "Focus",
                            TransmissionId = new Guid("d05d4a40-7fe2-4f62-aa4a-4cfa7394be7c")
                        },
                        new
                        {
                            Id = new Guid("e77990f8-4a55-4bea-a861-9fe8e40ed65a"),
                            BrandName = "Toyota",
                            EngineId = new Guid("ea66b050-2f0f-4184-856e-173de6aaa8af"),
                            ModelName = "Prius",
                            TransmissionId = new Guid("3d26cd66-1bd2-42cd-af14-eccc3618be26")
                        });
                });

            modelBuilder.Entity("Task_2.Models.ClientCar", b =>
                {
                    b.HasOne("Task_2.Models.Client", "Client")
                        .WithMany("ClientCars")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Task_2.Models.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Task_2.Models.Vehicle", b =>
                {
                    b.HasOne("Task_2.Models.Engine", "Engine")
                        .WithMany()
                        .HasForeignKey("EngineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Task_2.Models.Transmission", "Transmission")
                        .WithMany()
                        .HasForeignKey("TransmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Engine");

                    b.Navigation("Transmission");
                });

            modelBuilder.Entity("Task_2.Models.Client", b =>
                {
                    b.Navigation("ClientCars");
                });
#pragma warning restore 612, 618
        }
    }
}
